export const tabs = ['Nature', 'Gradient', 'New', 'Sports', 'Random', 'Animal'];
export const check = [
  '3D',
  'Cars',
  'City',
  'Night City',
  'Fantasy',
  'Girls',
  'Technologies',
  'Men',
  'Firework',
  'Space',
  'Texture',
  'Vector',
  'Art',
  'Dark',
  'Motercycles',
  'Forest',
  'Ocean',
  'UnderWater',
  'Aquarium',
  'Landscape',
  'blur',
];
